version: '3.8'

services:
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rungroopcourse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/rungroopcourse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"

volumes:
  pgdata:
