spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/rungroopcourse}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
# The above configuration uses environment variables if available (for Docker),
# otherwise falls back to localhost values (for local development)

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=test
spring.security.user.password=test
spring.jpa.show-sql=true