spring.datasource.url=jdbc:postgresql://localhost:5432/rungroopcourse
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=test
spring.security.user.password=test
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:postgresql://dpg-cvivu9i4d50c73c630t0-a/rungroopcourse
#spring.datasource.username=rungroopcourse_user
#spring.datasource.password=WdEAXmWidsdZMmNN3fveP3ETzKo1i5CA
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.security.user.name=test
#spring.security.user.password=test
#spring.jpa.show-sql=true